import React from 'react';

const ActivityList = [
  {
    "id": 11323,
    "moduleId": 0,
    "subModuleId": 4,
    "objectId": 10185,
    "remarks": null,
    "assignedOn": "2021-06-28T16:41:02.68",
    "dueDate": "2021-06-28T16:41:02.68",
    "assignedBy": 695,
    "assignedTo": 695,
    "actionId": "IDEwMTQyIDEwMTg1IA==",
    "actionData": "",
    "actionTaken": "Done",
    "isMandatory": 1,
    "activityType": "BID_PLAN_ACTIVITY",
    "isCompleted": 0,
    "workflowId": "",
    "completionDate": "2021-06-28T16:41:02.68",
    "navigationUrl": null,
    "companyId": 1,
    "approvalFor": "Tenders",
    "moduleName": "Tender to Contract",
    "subModuleName": null,
    "description": "NAME OF WORK",
    "delegetedFrom": 0,
    "isDelgated": 0
  },
 
  {
    "id": 474,
    "moduleId": 0,
    "subModuleId": 3,
    "objectId": 3042,
    "remarks": null,
    "assignedOn": "2021-06-04T13:50:09.14",
    "dueDate": "2021-06-09T13:50:09.14",
    "assignedBy": 695,
    "assignedTo": 695,
    "actionId": "Njk1IDMzMDQyQUJQMzg2",
    "actionData": "[{\"ActionName\":\"Approve\",\"ActionValue\":\"approved\",\"ActionId\":\"1\",\"IsPositive\":true},{\"ActionName\":\"Rejected\",\"ActionValue\":\"rejected\",\"ActionId\":\"1\",\"IsPositive\":false}]",
    "actionTaken": null,
    "isMandatory": 1,
    "activityType": "APPROVAL",
    "isCompleted": 0,
    "workflowId": "342e6f58-d699-4d40-8ed7-d3132cce7d08",
    "completionDate": "1753-01-01T00:00:00",
    "navigationUrl": "",
    "companyId": 1,
    "approvalFor": "Annual Business Plan",
    "moduleName": "Tender to Contract",
    "subModuleName": "Target Setting for Annual Business Plan",
    "description": "test sandy",
    "delegetedFrom": 0,
    "isDelgated": 0
  },
  {
    "id": 473,
    "moduleId": 0,
    "subModuleId": 3,
    "objectId": 3041,
    "remarks": null,
    "assignedOn": "2021-06-04T12:23:21.7",
    "dueDate": "2021-06-09T12:23:21.7",
    "assignedBy": 695,
    "assignedTo": 695,
    "actionId": "Njk1IDMzMDQxQUJQNzky",
    "actionData": "[{\"ActionName\":\"Approve\",\"ActionValue\":\"approved\",\"ActionId\":\"1\",\"IsPositive\":true},{\"ActionName\":\"Rejected\",\"ActionValue\":\"rejected\",\"ActionId\":\"1\",\"IsPositive\":false}]",
    "actionTaken": null,
    "isMandatory": 1,
    "activityType": "APPROVAL",
    "isCompleted": 0,
    "workflowId": "922e3a54-9d37-4da2-95fd-7f543c7b1b80",
    "completionDate": "1753-01-01T00:00:00",
    "navigationUrl": "",
    "companyId": 1,
    "approvalFor": "Annual Business Plan",
    "moduleName": "Tender to Contract",
    "subModuleName": "Target Setting for Annual Business Plan",
    "description": "Sunil Test",
    "delegetedFrom": 0,
    "isDelgated": 0
  },
  
  {
    "id": 397,
    "moduleId": 0,
    "subModuleId": 3,
    "objectId": 3028,
    "remarks": "rejected to test the flow",
    "assignedOn": "2021-05-22T05:57:05.083",
    "dueDate": "2021-05-27T05:57:05.083",
    "assignedBy": 695,
    "assignedTo": 695,
    "actionId": "Njk1IDMzMDI4QUJQOTM1",
    "actionData": "[{\"ActionName\":\"Approve\",\"ActionValue\":\"approved\",\"ActionId\":\"1\",\"IsPositive\":true},{\"ActionName\":\"Rejected\",\"ActionValue\":\"rejected\",\"ActionId\":\"1\",\"IsPositive\":false}]",
    "actionTaken": "rejected",
    "isMandatory": 1,
    "activityType": "PROCESS",
    "isCompleted": 1,
    "workflowId": "5261677f-f19d-45ae-b439-3130c3e4afb1",
    "completionDate": "2021-05-22T05:58:05.447",
    "navigationUrl": "",
    "companyId": 1,
    "approvalFor": "Annual Business Plan",
    "moduleName": "Tender to Contract",
    "subModuleName": "Target Setting for Annual Business Plan",
    "description": "Sunil's First ABP Plan",
    "delegetedFrom": 0,
    "isDelgated": 0
  },
  {
    "id": 396,
    "moduleId": 0,
    "subModuleId": 3,
    "objectId": 3028,
    "remarks": "i rejected it and then will restart",
    "assignedOn": "2021-05-22T05:40:50.687",
    "dueDate": "2021-05-27T05:40:50.687",
    "assignedBy": 695,
    "assignedTo": 695,
    "actionId": "Njk1IDMzMDI4QUJQMTY5",
    "actionData": "[{\"ActionName\":\"Approve\",\"ActionValue\":\"approved\",\"ActionId\":\"1\",\"IsPositive\":true},{\"ActionName\":\"Rejected\",\"ActionValue\":\"rejected\",\"ActionId\":\"1\",\"IsPositive\":false}]",
    "actionTaken": "rejected",
    "isMandatory": 1,
    "activityType": "PROCESS",
    "isCompleted": 1,
    "workflowId": "69d6e4b4-4d5c-4822-ac38-b59db2887cd1",
    "completionDate": "2021-05-22T05:43:11.253",
    "navigationUrl": "",
    "companyId": 1,
    "approvalFor": "Annual Business Plan",
    "moduleName": "Tender to Contract",
    "subModuleName": "Target Setting for Annual Business Plan",
    "description": "Sunil's First ABP Plan",
    "delegetedFrom": 0,
    "isDelgated": 0
  },
  {
    "id": 390,
    "moduleId": 0,
    "subModuleId": 3,
    "objectId": 3028,
    "remarks": "ggh",
    "assignedOn": "2021-05-20T08:32:45.37",
    "dueDate": "2021-05-25T08:32:45.37",
    "assignedBy": 695,
    "assignedTo": 695,
    "actionId": "Njk1IDMzMDI4QUJQOTY2",
    "actionData": "[{\"ActionName\":\"Approve\",\"ActionValue\":\"approved\",\"ActionId\":\"1\",\"IsPositive\":true},{\"ActionName\":\"Rejected\",\"ActionValue\":\"rejected\",\"ActionId\":\"1\",\"IsPositive\":false}]",
    "actionTaken": "approved",
    "isMandatory": 1,
    "activityType": "PROCESS",
    "isCompleted": 1,
    "workflowId": "85ba1804-a4c5-4559-b4ad-9c6d634a78e1",
    "completionDate": "2021-05-20T08:33:25.927",
    "navigationUrl": "",
    "companyId": 1,
    "approvalFor": "Annual Business Plan",
    "moduleName": "Tender to Contract",
    "subModuleName": "Target Setting for Annual Business Plan",
    "description": "Sunil's First ABP Plan",
    "delegetedFrom": 0,
    "isDelgated": 0
  }
]

export default ActivityList;